# Generated by Django 4.1.7 on 2023-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_pasport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Подтверждение аккаунта'),
        ),
    ]
