# Generated by Django 4.1.7 on 2023-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pasport',
            field=models.CharField(max_length=100, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
    ]
