# Generated by Django 4.1.7 on 2023-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_pasport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pasport',
            field=models.CharField(max_length=100, unique=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер телефона'),
        ),
    ]
