# Generated by Django 4.2.5 on 2023-10-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
    ]
