# Generated by Django 4.2.5 on 2023-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0004_groups_alter_news_options_remove_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата Публикации'),
        ),
    ]
